### ISSUE TITLE
nowa funkcjonalność

### ISSUE THREAD

**Issue by RadoslawBiereta** [annadrobek/ShoppingList#15]
*Potrzebujemy dodać kolejną funkcjonalność dla naszego projektu:*

- [ ] dodawanie produktów do listy

- [ ] proces logowania się użytkownika
- [ ] ???

**Comment by annadrobek** [comment]
Na razie skupmy się na zadaniu 1, jeżeli starczy czasu to przyjrzymy się zadaniu 2. Zagadnienie zarządzania userem/hasłem to temat rzeka. Jako 3 zadanie jest w kolejce skaner na androida.

**Comment by RadoslawBiereta** [comment]
Ok, działamy dalej

**Comment by annadrobek** [comment]
Dodałam kilka funkcjonalności. Czy jest to wystarczające?

**Comment by RadoslawBiereta** [comment]
Ok, mamy już dodawanie i usuwanie listy, dodawanie produktów, generowanie kodu QR
