### ISSUE TITLE
Aplikacja na telefon potzebna do czytania kodu QR

### ISSUE THREAD

**Issue by annadrobek** [annadrobek/ShoppingList#25]
Potrzebna aplikacja na telefon żeby można było z czytywać przygotowaną listę z aplikacji.
Radek ogarniesz to?

**Comment by RadoslawBiereta** [comment]
Ok, postaram się w najbliższych dniach stworzyć prostą aplikację mobilną, która umożliwi odczytanie przygotowanej listy z naszej aplikacji internetowej poprzez kod QR. Będzie to na Androida.

**Comment by RadoslawBiereta** [comment]
Pierwsza wersja gotowa, lada moment wrzucę do repozytorium
