### ISSUE TITLE
Grafika na stronę internetową

### ISSUE THREAD

**Issue by annadrobek** [annadrobek/ShoppingList#26]
Radku czy ta grafika co zrobiłeś jest ostateczna czy coś jeszcze powinniśmy zmienić?

**Comment by RadoslawBiereta** [comment]
A jak myślisz - oprawa graficzna to kwestia gustu - najważniejsze, żeby było funkcjonalne?

**Comment by annadrobek** [comment]
Myślę że na tym etapie ta grafika którą wybrałeś jest ok i może tak zostać.

**Comment by RadoslawBiereta** [comment]
Jeśli znajdę trochę czasu - to może jeszcze coś pozmieniam w htmlu odnośnie grafiki.
Więc zostawmy ten Issue open, żeby o tym pamiętać. :question:

**Comment by annadrobek** [comment]
ok.

**Comment by annadrobek** [comment]
Myślę że grafika jest ok i komponuje się to wszystko z apką mobilną. Zamykam zgłoszenie.

**Comment by annadrobek** [comment]
Zamykam.
