### ISSUE TITLE
Kolejne html-e #8 

### ISSUE THREAD

**Issue by annadrobek** [annadrobek/ShoppingList#27]
Radek czy będą jeszcze kolejne HTMLe? W Pull reqests wygląda jakbyś już to skończył. Czy to ostateczna wersja?

**Comment by RadoslawBiereta** [comment]
@annadrobek  Tak, to już ostateczna wersja. Chyba, że dodamy jeszcze jakąś nową funkcjonalność. :bulb:?
Możemy zaczynać planowanie zakupów :shopping_cart: :shopping: :smiley:
