### ISSUE TITLE
 Problem z uruchomieną aplikacją w kontenerze Docker

### ISSUE THREAD

**Issue by RadoslawBiereta** [annadrobek/ShoppingList#28]
Coś się chyba rozsypało w Dockerfile'u. Apka nie ładuje się w locallhost. @annadrobek zerknij proszę. :pray:

**Comment by annadrobek** [comment]
ok. Sprawdzę to. Mam informację że nie ładuje mi się jeden element który wszystko psuje. Postaram się naprawić jak najszybciej.

**Comment by annadrobek** [comment]
Powinno już działać:)

**Comment by RadoslawBiereta** [comment]
Tak, działa. Thanks :+1:
