### ISSUE TITLE
Readme

### ISSUE THREAD

**Issue by RadoslawBiereta** [annadrobek/ShoppingList#30]
Potrzebujemy udokumentować nasz projekt w pliku Readme.md. (Opisać projekt, jego funkcje, instrukcje oraz uruchamianie)

**Comment by annadrobek** [comment]
OK. dobry pomysł, myślę że razem możemy nad tym popracować. Zróbmy na bieżąco aktualizację. Na pewno trzeba dodać jeszcze funkcjonalności ze skanera kodu listy zakupowów.

**Comment by RadoslawBiereta** [comment]
Zrobiłem V2 pliku Readme.md. Proszę przejrzyj Pull Requesta i zaakceptuj go jeżeli uważasz, że jest w porządku.

**Comment by annadrobek** [comment]
Jest ok. dobra robota. Zaakceptowany. Czy uważasz że jeszcze powinniśmy coś zmienić?

**Comment by RadoslawBiereta** [comment]
Tylko jeśli uda nam się dodać tą aplikację mobilną na Androida. :iphone:
