### ISSUE TITLE
Powiększenie przycisku do skanowania Kodu QR

### ISSUE THREAD

**Issue by annadrobek** [annadrobek/ShoppingList#32]
Hej. Trzeba by było Powiększyć przycisk do skanowania Kodu QR bo na razie jest mało widoczny. Dałbyś radę?

**Comment by RadoslawBiereta** [comment]
Tak zrobiłem to przy okazji [](https://github.com/annadrobek/ShoppingList/issues/33)

**Comment by RadoslawBiereta** [comment]
https://github.com/annadrobek/ShoppingList/issues/33
