### ISSUE TITLE
Czcionka do poprawy

### ISSUE THREAD

**Issue by annadrobek** [annadrobek/ShoppingList#35]
Chciałam prosić o wyśrodkowanie czcionki oraz jej edycje, pogrubienie itp.

**Comment by RadoslawBiereta** [comment]
wstawiłem czcionkę podobną do pisma odręcznego, oczywiście darmowa z daFonts
![emulator](https://github.com/annadrobek/ShoppingList/assets/116495178/8ce240fd-5885-4e78-af20-eca93ca4861b)

**Comment by annadrobek** [comment]
ok. Super. Wygląda to fajnie
