### ISSUE TITLE
Zmiana nazwy aplikacji na SchoppingList

### ISSUE THREAD

**Issue by annadrobek** [annadrobek/ShoppingList#36]
Zmiana nazwy aplikacji na SchoppingList bo ta co jest to słaba

**Comment by RadoslawBiereta** [comment]
Czy aby na pewno ma być "SchoppingList"? Wolał bym nazwać ją "ShoppingList" :-)

**Comment by RadoslawBiereta** [comment]
Zrobione, jeżeli jednak ma być inna nazwa to otwórz issue
