### ISSUE TITLE
Zmiana kolorystyki aplikacji 

### ISSUE THREAD

**Issue by annadrobek** [annadrobek/ShoppingList#37]
Kolory zgodne z kolorystyką aplikacji webowej.

**Comment by RadoslawBiereta** [comment]
@annadrobek  masz chyba jednak duszę artysty :art: :art: :art: 😄 😄😄

**Comment by annadrobek** [comment]
Kolor zmieniony na #FDCCA8.

**Comment by RadoslawBiereta** [comment]
Kolor zmieniony na #FDCCA8, jest teraz taki sam jak w nagłówku aplikacji spring
