### ISSUE TITLE
Poprawki końcowe. Testy manualne.

### ISSUE THREAD

**Issue by annadrobek** [annadrobek/ShoppingList#40]
Cześć. Dzięki za współpracę. Czy mamy coś jeszcze do poprawy? Wydaje mi się że funkcjonalności działają, front end jest ok i apka na androida czyta poprawnie kod.  Przeprowadźmy jeszcze testy manualne.

**Comment by RadoslawBiereta** [comment]
Hej. Ok, oczywiscie. Zróbmy to niezależnie i skonsultujmy wnioski.

**Comment by annadrobek** [comment]
Dla mnie wszystko jest ok. Myślę że możemy zamykać zgłoszenie.

**Comment by annadrobek** [comment]
Zamykam bo nie mam uwag.
